### PR TITLE
Update project to Xcode 8 and convert to Swift 3

### PR DESCRIPTION
**Pull request by amorde**
Includes changing `AnyObject` to `Any`, updated `UnsafeMutablePointer` syntax, changes to named parameters in blocks, and any other changes caught by the syntax converter.

All tests pass.

Not sure if travis build will pass given that it expects Xcode 7.3

### CODE REVIEW

**Comment by kylef** [comment]
Thanks for this @amorde.

Could you update https://github.com/kylef/JSONSchema.swift/blob/master/.swift-version to be `3.0` and the Xcode version in `.travis.yml` (https://github.com/kylef/JSONSchema.swift/blob/master/.travis.yml#L2) to `xcode8`. Then the CI should pass and this will be good to go.

**Comment by amorde** [comment]
Hi @kylef, thanks for the quick response! I update the Xcode version before seeing your comment, so I've updated the swift version in another commit. I can squash these if you'd like

**Comment by amorde** [comment]
Build failed with the following error:
```
 xcodebuild: error: Failed to build project JSONSchema with scheme JSONSchema.
	Reason: A build only device cannot be used to run this target.
```

Not really sure how to fix that :/

**Comment by kylef** [comment]
@amorde I can take over with that. I will tweak the CI steps.

Thanks for your pull request @amorde, I'll try and get to this tomorrow and get a release supporting Swift 3.0 out.

**Comment by amorde** [comment]
👍 Awesome, thanks for your support!

**Comment by amorde** [comment]
@kylef Hi again, I went ahead and pushed changed which should fix the build issue and also bumped the version number since I haven't heard anything in a while regarding this

**Pull request merged**
